api/urls.py
from django.urls import path

from . import views

urlpatterns = [ 
    path("add_favorite/", 
         views.add_favorite, name="add_favorite"), 
    path("remove_favorite/<int:recipe_id>/", 
         views.remove_favorite, name="remove_favorite"), 
    path("add_wishlist/", 
         views.add_wishlist, name="add_wishlist"), 
    path("remove_wishlist/<int:recipe_id>/", 
         views.remove_wishlist, name="remove_wishlist"), 
    path("add_subscription/", 
         views.add_subscription, name="add_subscription"), 
    path("remove_subscription/<int:following_id>/", 
         views.remove_subscription, name="remove_subscription"), 
    path("<str:username>/<int:recipe_id>/remove/", 
         views.remove_recipe, name="remove_recipe"), 
    path("ingredients/", 
         views.get_ingredients, name="get_ingredients"), 
    path("print_wishlist/", 
         views.get_wishlist, name="get_wishlist"), 
] 

foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path

urlpatterns = [
    path("auth/", include("users.urls")),
    path('admin/', admin.site.urls),
    path('about/', include('django.contrib.flatpages.urls')),
    path('about-us/', views.flatpage, {'url': '/about-us/'}, name='about'),
    path('terms/', views.flatpage, {'url': '/terms/'}, name='terms'),
    path('about-author/', views.flatpage, {'url': '/about-author/'}, name='author'),
    path('about-spec/', views.flatpage, {'url': '/about-spec/'}, name='spec'),
    path("", include("api.urls")),
    path("", include("recipes.urls")),
]

handler404 = "foodgram.views.page_not_found"
handler500 = "foodgram.views.server_error"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.shortcuts import get_object_or_404
from multiselectfield import MultiSelectField

User = get_user_model()

BREAFAST = 'breakfast'
LUNCH = 'lunch'
DINNER = 'dinner'

TAG_CHOICES = ((BREAFAST, 'Завтрак'),
               (LUNCH, 'Обед'),
               (DINNER, 'Ужин'))


class Recipe(models.Model):
    """Рецепты"""
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="recipes",
        verbose_name="Автор")
    title = models.CharField(max_length=100, verbose_name="Название рецепта")
    pub_date = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата публикации")
    tags = MultiSelectField(choices=TAG_CHOICES, blank=True,
                            null=True, verbose_name="Теги")
    description = models.TextField(
        blank=True, null=True, verbose_name="Описание")
    time = models.PositiveIntegerField(verbose_name="Время приготовления")
    image = models.ImageField(
        upload_to="recipes/",
        blank=True, null=True,
        verbose_name="Изображение")

    class Meta:
        ordering = ["-pub_date"]
        verbose_name = 'Рецепты'
        verbose_name_plural = 'Рецепты'

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    """Ингредиенты"""
    title = models.CharField(
        max_length=150, verbose_name="Название ингредиента")
    dimension = models.CharField(
        max_length=25, verbose_name="Единица измерения")

    class Meta:
        verbose_name = 'Ингредиенты'
        verbose_name_plural = 'Ингредиенты'

    def __str__(self):
        return f"{self.title} / {self.dimension}"


class RecipeIngredient(models.Model):
    """Описание ингредиентов и их колличества для рецепта"""
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, verbose_name="Рецепт")
    ingredient = models.ForeignKey(
        Ingredient, on_delete=models.CASCADE, verbose_name="Ингредиент")
    amount = models.PositiveIntegerField(verbose_name="Количество")

    def add_ingredient(self, recipe_id, title, amount):
        ingredient = get_object_or_404(Ingredient, title=title)
        return self.objects.get_or_create(recipe_id=recipe_id,
                                          ingredient=ingredient, amount=amount)

templates/base.html
<!doctype html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Рецепты{% endblock %} | Продуктовый помощник</title>
    {% block static %}
    <!-- Static -->
    {% endblock %}
</head>

<body class="body">
    <header class="header">
        <nav class="nav">
            <div class="nav__container container">
                <ul class="nav__items list">
                    {% url 'index' as index %}
                        <li class="nav__item {% if request.path  == index %}nav__item_active{% endif %}"><a href="{% url 'index' %}"
                                class="nav__link link">Рецепты</a></li>
                        {% if request.user.is_authenticated %}
                        {% url 'feed' as feed %}
                        <li class="nav__item {% if request.path  == feed %}nav__item_active{% endif %}"><a href="{% url 'feed' %}"
                                class="nav__link link">Мои подписки</a></li>
                        {% url 'new' as new %}
                        <li class="nav__item {% if request.path  == new %}nav__item_active{% endif %}"><a href="{% url 'new' %}"
                                class="nav__link link">Создать рецепт</a></li>
                        {% url 'favorites' as favorites %}
                        <li class="nav__item {% if request.path  == favorites %}nav__item_active{% endif %}"><a href="{% url 'favorites' %}"
                                class="nav__link link">Избранное</a></li>
                        {% url 'wishlist' as wishlist %}
                        {% load wishlist_count %}
                        <li class="nav__item {% if request.path  == wishlist %}nav__item_active{% endif %}"><a href="{% url 'wishlist' %}"
                                class="nav__link link">Список покупок</a> <span class="badge badge_style_blue nav__badge"
                                id="counter">{{ request.user|wishlist_count }}</span></li>
                    {% endif %}
                </ul>
                <ul class="nav__items list">
                    {% if request.user.is_authenticated %}
                        <li class="nav__item"><a href="{% url 'password_change' %}" class="nav__link link">Изменить
                                пароль</a></li>
                        <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
                    {% else %}
                        <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
                        <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать
                                аккаунт</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="main container">
        {% block content %}
        <!-- Содержимое страницы -->
        {% endblock %}
    </main>

    <footer class="footer">
        <div class="footer__container container">
            <a href="{% url 'index' %}" class="footer__brand link">Продуктовый помощник</a>
            <a href="{% url 'author' %}" class="footer__brand link">Об авторе</a> - <a href="{% url 'spec' %}" class="footer__brand link">Технологии</a>
        </div>
    </footer>

    {% block script %}
    <!-- Scripts -->
    {% endblock %}
</body>

</html>

templates/favorites.html
{% extends "base.html" %}
{% block title %}Избранное{% endblock %}

{% load static %}
{% block static %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block content %}
<div class="main__header">
    <h1 class="main__title">Избранное</h1>
    {% include 'components/tags.html' %}
</div>

{% csrf_token %}
<div class="card-list">
    {% for recipe in page %}
        <div class="card" data-id="{{ recipe.id }}">
            {% load thumbnail %}
            {% thumbnail recipe.image "364x240" crop="center" upscale=True as im %}
            <a href="{% url 'recipe' recipe.author.username recipe.id %}" class="link" target="_blank"><img
                    src="{{ im.url }}" alt="{{ recipe.title }}" class="card__image"></a>
            {% endthumbnail %}
            <div class="card__body">
                <a class="card__title link" href="{% url 'recipe' recipe.author.username recipe.id %}"
                    target="_blank">{{ recipe.title }}</a>
                <ul class="card__items">
                    {% if "lunch" in recipe.tags %}
                        <li class="card__item"><span class="badge badge_style_green">Обед</span></li>
                    {% endif %}
                    {% if "breakfast" in recipe.tags %}
                        <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>
                    {% endif %}
                    {% if "dinner" in recipe.tags %}
                        <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>
                    {% endif %}
                </ul>
                <div class="card__items card__items_column">
                    <p class="card__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
                    <p class="card__text"><span class="icon-user"></span> <a href="{% url 'user' recipe.author.username %}"
                            style="color: black">{{ recipe.author.get_full_name }}</a></p>
                </div>
            </div>
            {% if request.user.is_authenticated %}
            <div class="card__footer">
                {% load check_atribute %}
                {% if recipe|check_wishlist:request.user %}
                    <button class="button button_style_light-blue-outline" name="purchases"><span
                            class="icon-check button__icon"></span>Рецепт добавлен</button>
                {% else %}
                    <button class="button button_style_light-blue" name="purchases" data-out><span
                            class="icon-plus button__icon"></span>Добавить в покупки</button>
                {% endif %}
                <button class="button button_style_none" name="favorites"><span
                        class="icon-favorite icon-favorite_active"></span></button>
            </div>
            {% endif %}
        </div>
    {% endfor %}
</div>

{% if page.has_other_pages %}
    {% include "components/paginator.html" with items=page paginator=paginator %}
{% endif %}

{% endblock %}

{% block script %}
<script src="{% static 'js/components/MainCards.js' %}"></script>

<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/components/Favorites.js' %}"></script>

<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>

<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'favorite.js' %}"></script>
{% endblock %}

templates/feed.html
{% extends "base.html" %}
{% block title %}Мои подписки{% endblock %}

{% load static %}
{% block static %}
<link rel="stylesheet" href="{% static 'pages/myFollow.css' %}">
{% endblock %}

{% block content %}
{% csrf_token %}
<div class="main__header">
    <h1 class="main__title">Мои подписки</h1>
</div>

{% load count_calc %}
<div class="card-list">
    {% for author in page %}
        <div class="card-user" data-author="{{ author.id }}">
            <div class="card-user__header">
                <h2 class="card-user__title">{{ author.get_full_name }}</h2>
            </div>
            <div class="card-user__body">
                <ul class="card-user__items">
                    {% if author.recipes.all.count > 3 %}
                        {% for recipe in author.recipes.all|slice:":3" %}
                            <li class="card-user__item">
                                <div class="recipe">
                                    {% load thumbnail %}
                                    {% thumbnail recipe.image "72x72" crop="center" upscale=True as im %}
                                    <img src="{{ im.url }}" alt="{{ recipe.title }}" class="recipe__image">
                                    {% endthumbnail %}
                                    <h3 class="recipe__title">{{ recipe.title }}</h3>
                                    <p class="recipe__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
                                </div>
                            </li>
                        {% endfor %}
                        <li class="card-user__item">
                            <a href="{% url 'user' author.username %}" class="card-user__link link">Еще
                                {{ author.recipes.all.count | count_calc }} </a>
                        </li>
                    {% else %}
                        {% for recipe in author.recipes.all %}
                            <li class="card-user__item">
                                <div class="recipe">
                                    {% load thumbnail %}
                                    {% thumbnail recipe.image "72x72" crop="center" upscale=True as im %}
                                    <img src="{{ im.url }}" alt="{{ recipe.title }}" class="recipe__image">
                                    {% endthumbnail %}
                                    <h3 class="recipe__title">{{ recipe.title }}</h3>
                                    <p class="recipe__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
                                </div>
                            </li>
                        {% endfor %}
                        <li class="card-user__item">
                            <a href="{% url 'user' author.username %}" class="card-user__link link">Перейти к автору... </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <div class="card-user__footer">
                <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
            </div>
        </div>
    {% endfor %}
</div>

{% if page.has_other_pages %}
    {% include "components/paginator.html" with items=page paginator=paginator %}
{% endif %}

{% endblock %}

{% block script %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/MyFollow.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'myFollow.js' %}"></script>
{% endblock %}

templates/form_recipe.html
{% extends "base.html" %}
{% block title %}{{ form_title }}{% endblock %}

{% load static %}
{% block static %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% block content %}
{% load add_class %}
<div class="main__header">
    <h1 class="main__title">{{ form_title }}</h1>
</div>
<div class="form-container">
    <form class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form__group">
            <label for="{{ form.title.id_for_label }}" class="form__label">Название рецепта</label>
            <div class="form__field-group">
                {{ form.title|addclass:"form__input" }}
                <span class="form__error">{{ form.title.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <p class="form__label">Теги</p>
            <div class="form__field-group">
                <div class="tags">
                    <div class="tags__item">
                        <input type="checkbox" name="tags" value="breakfast" id="id_breakfast"
                            class="tags__checkbox tags__checkbox_style_orange" {% if is_breakfast %}checked{% endif %}>
                        <label for="id_breakfast" class="tags__label">Завтрак</label>
                    </div>
                    <div class="tags__item">
                        <input type="checkbox" name="tags" value="lunch" id="id_lunch"
                            class="tags__checkbox tags__checkbox_style_green" {% if is_lunch %}checked{% endif %}>
                        <label for="id_lunch" class="tags__label">Обед</label>
                    </div>
                    <div class="tags__item">
                        <input type="checkbox" name="tags" value="dinner" id="id_dinner"
                            class="tags__checkbox tags__checkbox_style_purple" {% if is_dinner %}checked{% endif %}>
                        <label for="id_dinner" class="tags__label">Ужин</label>
                    </div>
                </div>
                <span class="form__error">{{ form.tags.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <label for="nameIngredient" class="form__label">Ингредиенты</label>
            <div class="form__field-group">
                <div class="form__field-group-ingredientes">
                    <div class="form__dropdown">
                        <input type="text" id="nameIngredient" class="form__input">
                        <div class="form__dropdown-items"></div>
                    </div>
                    <input type="number" id="cantidad" class="form__input" min="0">
                    <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                </div>
                <div class="form__field-group-ingredientes-container">
                    {% for ingredient in ingredients %}
                        <div class="form__field-item-ingredient" id="ing_{{ ingredient.ingredient.id }}"><span>
                                {{ ingredient.ingredient.title }} {{ ingredient.amount }}
                                {{ ingredient.ingredient.dimension }}</span> <span class="form__field-item-delete"></span>
                            <input id="nameIngredient_{{ ingredient.ingredient.id }}"
                                name="nameIngredient" type="hidden"
                                value="{{ ingredient.ingredient.title }}">
                            <input id="valueIngredient_{{ ingredient.ingredient.id }}"
                                name="valueIngredient" type="hidden"
                                value="{{ ingredient.amount }}">
                            <input id="unitsIngredient_{{ ingredient.ingredient.id }}"
                                name="unitsIngredient" type="hidden"
                                value="{{ ingredient.ingredient.dimension }}">
                    </div>
                    {% endfor %}
                </div>
                <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                <span class="form__error"></span>
            </div>
        </div>
        <div class="form__group">
            <label for="{{ form.time.id_for_label }}" class="form__label">Время приготовления</label>
            <div class="form__field-group form__field-group_time">
                {{ form.time|addclass:"form__input" }}
                <label for="id_time" class="form__label">минут</label>
                <span class="form__error">{{ form.time.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <label for="{{ form.description.id_for_label }}" class="form__label">Описание</label>
            <div class="form__field-group">
                {{ form.description|addclass:"form__textarea" }}
                <span class="form__error">{{ form.description.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <span class="form__label">Загрузить фото</span>
            <div class="form__field-group">
                <div class="form__field-group">
                    <label for="{{ form.image.id_for_label }}" class="form__file-button">Выбрать файл</label>
                    <input type="file" name="{{ form.image.name }}" id="{{ form.image.id_for_label }}" class="form__file">
                    <span class="form__error">{{ form.image.errors }}</span>
                </div>
            </div>
        </div>
        <div class="form__footer">
            <button class="button button_style_blue">{{ btn_caption }}</button> 
            {% if recipe %}
                <a style="margin-left: 2.5em" href="{% url 'remove_recipe' recipe.author.username recipe.id %}" class="form__ingredient-link">Удалить</a>
            {% endif %}
        </div>
    </form>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/utils/debouncing.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'formRecipe.js' %}"></script>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}Рецепты{% endblock %}

{% load static %}
{% block static %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block content %}
<div class="main__header">
    <h1 class="main__title">Рецепты</h1>
    {% include 'components/tags.html' %}
</div>

{% csrf_token %}
<div class="card-list">
    {% for recipe in page %}
        {% include 'components/recipe.html' %}
    {% endfor %}
</div>


{% if page.has_other_pages %}
    {% include "components/paginator.html" with items=page paginator=paginator %}
{% endif %}

{% endblock %}

{% block script %}
<script src="{% static 'js/components/MainCards.js' %}"></script>

<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/components/Favorites.js' %}"></script>

<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>

<script src="{% static 'js/api/Api.js' %}"></script>
{% if user.is_authenticated %}
    <script src="{% static 'indexAuth.js' %}"></script>
{% else %}
    <script src="{% static 'indexNotAuth.js' %}"></script>
{% endif %}
{% endblock %}

templates/recipe_page.html
{% extends "base.html" %}
{% block title %}{{ recipe.title }}{% endblock %}

{% load static %}
{% block static %}
<link rel="stylesheet" href="{% static 'pages/single.css' %}">
{% endblock %}

{% load check_atribute %}

{% block content %}
{% csrf_token %}
<div class="single-card" data-id="{{ recipe.id }}" data-author="{{ recipe.author.id }}">
    {% load thumbnail %}
    {% thumbnail recipe.image "480x480" crop="center" upscale=True as im %}
    <img src="{{ im.url }}" alt="{{ recipe.title }}" class="single-card__image" width="480" height="480">
    {% endthumbnail %}
    <div class="single-card__info">
        <div class="single-card__header-info">
            <h1 class="single-card__title">{{ recipe.title }}</h1>
            <div class="single-card__favorite">
                {% if request.user.is_authenticated %}
                    {% if recipe|check_favorite:request.user %}
                        <button class="button button_style_none" name="favorites"><span
                                class="icon-favorite icon-favorite_big  icon-favorite_active"></span></button>
                    {% else %}
                        <button class="button button_style_none" name="favorites" data-out><span
                                class="icon-favorite icon-favorite_big"></span></button>
                    {% endif %}
                {% endif %}
                <div class="single-card__favorite-tooltip tooltip">Добавить в избранное</div>
            </div>
        </div>
        <ul class="single-card__items">
            {% load add_class %}
            {% load get_tag_value %}
            {% for tag in recipe.tags %}
                <li class="single-card__item"><span class="{{ tag|class_tag }}">{{ tag|get_tag_value }}</span></li>
            {% endfor %}
        </ul>
        <div class="single-card__items single-card__items_column">
            <p class="single-card__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
            <ul class="single-card__items">
                <li class="single-card__item">
                    <p class="single-card__text"><span class="icon-user"></span><a href="{% url 'user' recipe.author.username %}"
                        style="color: black"> {{ recipe.author.get_full_name }}</a></p>
                </li>
                {% if request.user == recipe.author %}
                    <li class="single-card__item"> <a style="margin-left: 2.5em" href="{% url 'edit_recipe' recipe.author.username recipe.id %}"
                            class="single-card__text">Редактировать рецепт</a></li>
                {% endif %}
            </ul>
        </div>
        {% if request.user.is_authenticated %}
        <ul class="single-card__items">
                {% if recipe|check_wishlist:request.user %}
                    <li class="single-card__item"><button class="button button_style_light-blue-outline" name="purchases"><span
                                class="icon-check"></span>Рецепт добавлен</button></li>
                {% else %}
                    <li class="single-card__item"><button class="button button_style_blue" name="purchases" data-out><span
                                class="icon-plus"></span>Добавить в покупки</button></li>
                {% endif %}
                {% if request.user != recipe.author %}
                    {% if recipe.author|check_subscription:request.user %}
                        <li class="single-card__item"><button class="button button_style_light-blue button_size_subscribe"
                                name="subscribe">Отписаться от автора</button></li>
                    {% else %}
                        <li class="single-card__item"><button class="button button_style_light-blue button_size_subscribe"
                                name="subscribe" data-out>Подписаться на автора</button></li>
                    {% endif %}
                {% endif %}
            </ul>
        {% endif %}
        <div class="single-card__section">
            <h3 class="single-card__section-title">Ингридиенты:</h3>
            <div class="single-card__items single-card__items_column">
                {% for ingredient in ingredients %}
                    {{ ingredient.dimension }}
                    <p class=" single-card__section-item">{{ ingredient.ingredient.title }} -
                        {{ ingredient.amount }} {{ ingredient.ingredient.dimension }}</p>
                {% endfor %}
            </div>
        </div>
        <div class="single-card__section">
            <h3 class="single-card__section-title">Описание:</h3>
            <p class=" single-card__section-text">{{ recipe.description | safe }}</p>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/components/Favorites.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'js/config/config.js' %}"></script>

<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/SingleCard.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>

<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'singlePage.js' %}"></script>
{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% block title %}Регистрация{% endblock %}

{% load static %}
{% block static %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% load add_class %}
{% block content %}
<div class="main__header">
<h1 class="main__title">Регистрация</h1>
</div>
<div class="form-container">
    <form class="form" method="post" action="{% url 'signup' %}">
        {% csrf_token %}
        <div class="form__group">
            <label for="{{ form.first_name.id_for_label }}" class="form__label">Имя</label>
            <div class="form__field-group">
                {{ form.first_name|addclass:"form__input" }}
                <span class="form__error">{{ form.first_name.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <label for="{{ form.username.id_for_label }}" class="form__label">Имя пользователя</label>
            <div class="form__field-group">
                {{ form.username|addclass:"form__input" }}
                <span class="form__error">{{ form.username.errors }}
                </span>
            </div>
        </div>
        <div class="form__group">
            <label for="{{ form.email.id_for_label }}" class="form__label">Адрес электронной почты</label>
            <div class="form__field-group">
                {{ form.email|addclass:"form__input" }}
                <span class="form__error">{{ form.email.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <label for="{{ form.password1.id_for_label }}" class="form__label">Пароль</label>
            <div class="form__field-group">
                {{ form.password1|addclass:"form__input" }}
                <span class="form__error">{{ form.password1.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <label for="{{ form.password2.id_for_label }}" class="form__label">Повторите пароль</label>
            <div class="form__field-group">
                {{ form.password2|addclass:"form__input" }}
                <span class="form__error">{{ form.password2.errors }}</span>
            </div>
        </div>
        <div class="form__footer">
            <button class="button button_style_blue">Создать аккаунт</button>
        </div>
    </form>
</div>
{% endblock %}